[package]
name = "achiever"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
yaml-validator = {version = "0.1.0"}
gluesql = {version = "0.7", default-features = true, features = ["sorter", "alter-table", "index"]}
sled = {version = "0.34.6", features = ["compression", "zstd"]}
yaml-validator-cli = {version="0.1.0"}
tantivy = {version="0.15.2"}
