[package]
name = "achiever"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
yaml-validator = {version = "0.1.0"}
gluesql = {version = "0.7", default-features = true, features = ["sorter", "alter-table", "index"]}
sled = {version = "0.34.6", features = ["compression", "zstd"]}
yaml-validator-cli = {version="0.1.0"}
tantivy = {version="0.15.2"}
stop-words = {version="0.4.0"}
rust-stemmers = {version="1.2.0"}
dirs = {version="3.0.2"}
uuid = {version="0.8.2"}
argparse = {version="0.2.2"}
validator = { version = "0.12", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = {version="0.8"}
i18n-embed = {version="0.10"}
xtr = {version="0.1.6"}
tr = {version="0.1.6"}
